# -*- conf -*-

font=monospace:size=10:antialias=true:autohint=true

[colors]
alpha=0.96
background=282828
foreground=e2d3ba
regular0=282828 # black
regular1=ea6962 # red
regular2=a9b665 # green
regular3=d8a657 # yellow
regular4=7daea3 # blue
regular5=d3869b # magenta
regular6=89b482 # cyan
regular7=d4be98 # white
bright0=928374 # black
bright1=ef938e # red
bright2=bbc585 # green
bright3=e1bb7e # yellow
bright4=9dc2ba # blue
bright5=e1acbb # magenta
bright6=a7c7a2 # cyan
bright7=e2d3ba # white

[key-bindings]
clipboard-copy=Mod1+Shift+c XF86Copy
clipboard-paste=Mod1+Shift+v XF86Paste
font-increase=Mod1+Shift+k Control+KP_Add
font-decrease=Mod1+Shift+j Control+KP_Subtract
