# ~/.config/X11/xinitrc

slstatus &
xcompmgr &
dunst &

if xrandr | grep "HDMI1 connected"; then
    xrandr --output HDMI1 --auto --same-as eDP1
fi

feh --no-fehbg --bg-fill --randomize $HOME/Pictures/Backgrounds/

xrdb -load ~/.config/X11/xresources

exec dwm
